version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./web:/web
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - djangonetwork
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: django
    # depends_on:
    #   - db
    volumes:
      - ./web:/web
    expose:
      - "8000"
    # links:
    #   - redis
    # env_file:
    #   - ./.envs/.django
    networks:
      - djangonetwork
  # db:
  #   build:
  #     context: .
  #     dockerfile: compose/postgres/Dockerfile
  #   container_name: pz01
  #   env_file:
  #     - ./.envs/.postgres
  #   volumes:
  #     - local_postgres_data:/var/lib/postgresql/data
  #     - local_postgres_data_backups:/backups
  #   networks:
  #     - djangonetwork
  # redis:
  #   image: redis:alpine
  #   container_name: rz01
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - djangonetwork

networks:
  djangonetwork:
    driver: bridge
